[package]
name = "annals"
version = "0.0.0"
authors = [""]

[dependencies]
failure = "0.1"
itertools = "0.7"
pest = "1.0"
pest_derive = "*"
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
