[package]
name = "annals"
version = "0.1.0"
authors = ["cthwaite"]

[dependencies]
failure = "0.1"
lazy_static = "1.1.0"
rand = "0.5"
regex = "1.0.5"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
titlecase = "0.10"
