[package]
name = "annals"
version = "0.1.0"
authors = ["cthwaite"]
edition = "2018"

[dependencies]
lazy_static = "^1.4"
rand = "^0.7"
serde = {version = "^1.0", features = ["derive"]}
serde_yaml = "^0.8"
titlecase = "^1.1"
regex = "^1.3"
